# .github/workflows/release.yml

name: Create and Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⛔️ Verify tag is on the main branch
        run: |
          git branch -r --contains ${{ github.ref_name }} | grep 'origin/main$'
          echo "✅ Release tag is on the main branch. Proceeding."

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata from Git tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rafaelqsantosrqs/opencontact-frontend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push the release image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
